name: Build, Run, and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-html-nginx:latest .

    - name: Create and run container
      run: |
        docker run -d -p 500:80 --name simple-html-nginx ${{ secrets.DOCKER_USERNAME }}/simple-html-nginx:latest
        sleep 10 # Wait for the container to start

    - name: Test the container
      run: curl -f http://localhost:500

    - name: Stop and remove container
      run: |
        docker stop simple-html-nginx
        docker rm simple-html-nginx

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-html-nginx:latest